---
- name: install nginx
  yum: name='{{ item }}' state=latest
  with_items:
    - nginx

- name: nginx default configuration
  copy: src=files/nginx.conf
        dest=/etc/nginx/nginx.conf
        backup=yes
  notify:
    - restart nginx

- name: copy upstream configuration template
  copy: src=files/tomcat_upstream.conf
        dest=/etc/nginx/conf.d/tomcat_upstream.conf
        backup=yes
  when: proxy | length | int > 0
  notify:
    - restart nginx

- name: copy proxy pass configuration
  copy: src=files/tomcat_proxypass.conf
        dest=/etc/nginx/default.d/tomcat_proxypass.conf
        backup=yes
  when: proxy | length | int > 0
  notify:
    - restart nginx

- name: setup proxypass hosts
  lineinfile: dest=/etc/nginx/conf.d/tomcat_upstream.conf
              state=present
              regexp='[\s]* server[\s]*{{ item }}'
              insertafter='^upstream backend {'
              line='    server {{ item }}:{{ tomcat_port }};'
              backup=yes
  with_items: '{{ proxy }}'
  when: proxy | length | int > 0
  notify:
    - restart nginx
