---
- name: disable root login via ssh
  lineinfile: dest=/etc/ssh/sshd_config
              regexp='^[P|p]ermit[R|r]oot[L|l]ogin'
              insertafter='^#[\s]*[P|p]ermit[R|r]oot[L|l]ogin'
              line='PermitRootLogin no'
              state=present
              create=no
  notify: restart ssh

- name: do not permit empty password login
  lineinfile: dest=/etc/ssh/sshd_config
              regexp='^[P|p]ermit[E|e]mpty[P|p]asswords'
              insertafter='^#[P|p]ermit[E|e]mpty[P|p]asswords'
              line='PermitEmptyPasswords no'
              state=present
              create=no
  notify: restart ssh
